<a href="https://colab.research.google.com/github/Mijba/assignment-submission-demo/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
a = np.random.random((3,5))
a

array([[0.66055768, 0.71838482, 0.88160053, 0.10908877, 0.64030848],
       [0.20132798, 0.42380328, 0.22747082, 0.05914878, 0.69732455],
       [0.45324425, 0.66563929, 0.6992406 , 0.61557339, 0.33729967]])

In [5]:
a = np.random.randint((3,5))
a

array([1, 2])

In [16]:
a = np.random.randint(10,50, (6,5))
a

array([[34, 44, 10, 21, 27],
       [22, 45, 20, 42, 44],
       [25, 36, 30, 38, 27],
       [12, 34, 36, 48, 28],
       [45, 40, 32, 25, 34],
       [45, 40, 25, 39, 27]])

In [17]:
a[3:5,:3]

array([[12, 34, 36],
       [45, 40, 32]])

In [18]:
a[2:4,2:]

array([[30, 38, 27],
       [36, 48, 28]])